# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f707855f72ec8df40c49f36a432f085d7764a11caecd52b7ede3a022c3119fca3659ce623d6c74029d78e41bc14c032da626bb0f77d3f0f14db757679c0a7b8

test:
  secret_key_base: d0e394ecc91bcd0febf2801db472075c400414ce262901a13174043d394a2cb3aa5cb90210ec2fe50af0c7fedd633a0d066e35a5c03ab1c36e221b0a76899922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
